s=int(input("enter your roll number"))
if s==401:
    print("name: Aradadi Sai Kiriti\n")
    print("group: ECE\n")
    print("section: A\n")
    print("mailid: 19p31a0401@acet.ac.in\n")
elif s==402:
    print("name:ADABALA MANIKANTA \n")
    print("group: ECE\n")
    print("section: A\n")
    print("mailid:19P31A0502@acet.ac.in\n")
elif s==403:
     print("name:AKASAPU LALITHA \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:1931a0404@acet.ac.in\n")
elif s==404:
     print("name:ALLADA DURGA SAI HEMANTH \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0404@acet.ac.in\n")
elif s==405:
     print("name:AMMANAMANCHI SREEYA\n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0405@acet.ac.in\n")

elif s==406:
     print("name:BANDI SHIVA RAMA KRISHNA \n")
     print("group: ECE\n")
     print("section :A\n")
     print("mailid : 19p31a0406@acet.ac.in\n")
elif s==407:
     print("name:BHIMANADHAMJANKI RAM \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0407@acet.ac.in\n")
elif s==408:
     print("name:CHAGNTI VENKATA SAI \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0408@acet.ac.in\n")

elif s==409:
     print("name:CHAPPA RAJESH \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0409@acet.ac.in\n")
elif s==410:
     print("name:CHEEKALA UMESH KUMAR \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0410qcet.ac.in\n")
elif s==411:
     print("name:DANGETI MANIKANTA RAJU \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0411@acet.ac.in\n")
elif s==412:
     print("name: DASI KARTHIK\n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0412@acet.ac.in\n")
elif s==413:
     print("name:DEVAKIVADA BHAVANA SANDHYA \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0413@acet.ac.in\n")
elif s==414:
     print("name: DHULIPUDI SITAMAHALAKSHMI\n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0414@acet.ac.in\n")
elif s==415:
     print("name:EPI RAMESH  \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0415@acet.ac.in\n")
elif s==416:
     print("name:GANDI DURGAMAHESH \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0416@acet.ac.in\n")
elif s==417:
     print("name:garimella venkata ramasarayaamurutha \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0417@acet.ac.in\n")
elif s==418:
     print("name:GOLI NAVYAVASAI \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0418@acet.ac.in\n")
elif s==419:
     print("name:GONTHINA RAMYA SANJU SREE \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0419@acet.ac.in\n")
elif s==420:
     print("name:JAKKA SAI VINOD \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0420@acet.ac.in\n")
elif s==421:
     print("name:KALE BHASKARA SRINIVAS \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0421@acet.ac.in\n")
elif s==422:
     print("name:KANDALA VISWA SAIKOWSIK \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0422@acet.ac.in\n")
elif s==423:
     print("name:KARELLA MURALI \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0423@acet.ac.in\n")
elif s==424:
     print("name:KATHI V V SATYA SAI MANIKANTA SANDEEP \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0424@acet.ac.in\n")
elif s==425:
     print("name:KHUDAVAN SHAIK \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0425@acet.ac.in\n")
elif s==426:
     print("name:KILLI KRISHNA PRIYA \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0426@acet.ac.in\n")
elif s==427:
     print("name:KIRLAMPALLI DURGA SATYANARAYANA \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0427@acet.ac.in\n")
elif s==428:
     print("name:KOPPARATHI VENKATA AKASH \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0428@acet.ac.in\n")
elif s==429:
     print("name:KOPPISETTI SIVA PARAVATHI \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0429@acet.ac.in\n")
elif s==430:
     print("name:KOTHARU PHANI HARSHITHA \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0430@acet.ac.in\n")
elif s==431:
     print("name:KOTTAKKI SRINIVAS PAVAN KUMAR \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0431@acet.ac.in\n")
elif s==432:
     print("name:KUMPATLA ARJUN \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0432@acet.ac.in\n")
elif s==433:
     print("name:LINGAMPALLI DURGA RAJU \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0433@acet.ac.in\n")
elif s==434:
     print("name:MADHAVARAPU ESWARI \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0434@acet.ac.in\n")
elif s==435:
     print("name:MANEPALLI HRUSHITHIA \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0435@acet.ac.in\n")
elif s==436:
     print("name:MUSAMALLA MAMATHA\n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0436@acet.ac.in\n")
elif s==437:
     print("name:NS VENKATA SHESHA SAI NIKESH KOMMURI \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0437@acet.ac.in\n")
elif s==438:
     print("name:NAMBURI SATYA KAMALA SUKANYA \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0438@acet.ac.in\n")
elif s==439:
     print("name:NALU GANESH CHAITAY\NYA \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0439@acet.ac.in\n")
elif s==440:
     print("name:OLETI GANGA SRI \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0440@acet.ac.in\n")
elif s==441:
     print("name:PAPADASU VEERA VENKATA SANTHOSH REDDY \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0441@acet.ac.in\n")
elif s==442:
     print("name:PAVANI SATYA ANITHA DEGALA \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0442@acet.ac.in\n")
elif s==443:
     print("name:PILLI VINITHA \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0443@acet.ac.in\n")
elif s==444:
     print("name:POKALA KRISHNA VAMSI \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0444@acet.ac.in\n")
elif s==446:
     print("name:POLISETTI V V N M MAHALAKSHMI RAO \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0446@acet.ac.in\n")
elif s==447:
     print("name:SAILAV CHNDRIKA \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0447@acet.ac.in\n")
elif s==448:
     print("name:SALIA LAKSHMI SAHITHI \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0448@acet.ac.in\n")
elif s==449:
     print("name:SAJJA SRI HARSHITHA \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0449@acet.ac.in\n")
elif s==450:
     print("name:SAMUDRALA HEMANTH \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0415@acet.ac.in\n")
elif s==451:
     print("name:SAREPALLI PAVAN KUUMAR \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0451@acet.ac.in\n")
elif s==452:
     print("name:SATHI NAGA ESWAR REDDY \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0452@acet.ac.in\n")
elif s==453:
     print("name:SATYAMSETTI SIVA RAMAKISHNA \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0453@acet.ac.in\n")

elif s==454:
     print("name:SESETTI RAMYA \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0454@acet.ac.in\n")
elif s==455:
     print("name:SIDDNA PAVAN KUMAR \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0455@acet.ac.in\n")
elif s==456:
     print("name:SIDDA RAJITHA \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0456@acet.ac.in\n")
elif s==457:
     print("name:TUMMALAPALLI VIJYA LAKSHMI DURGA \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0457@acet.ac.in\n")
elif s==458:
     print("name:VANKYA ANURADHA \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0458@acet.ac.in\n")
elif s==459:
     print("name:VEELU HARSHA KUMAR \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0459@acet.ac.in\n")
elif s==460:
     print("name:YARRLGADDA SRI VIDHYA \n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0460@acet.ac.in\n")
elif s==461:
     print("name:YARRAMSETTY SIVA SATYANARAYANA\n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0461@acet.ac.in\n")

elif s==462:
     print("name: YEDIDA NAGA SURYA CHANDRA SAI LAKSHMI\n")
     print("group: ECE\n")
     print("section: A\n")
     print("mailid:19p31a0462@acet.ac.in\n")
